// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATJkDHjwD62qG7xX4IRysm_NIId98oXJ4',
    appId: '1:873700316255:web:885660804f3b0bfeefb7ea',
    messagingSenderId: '873700316255',
    projectId: 'econtrollectricity',
    authDomain: 'econtrollectricity.firebaseapp.com',
    databaseURL: 'https://econtrollectricity-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'econtrollectricity.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf_t2TDkpnsLv-58WV8CLBe9HwJRU2JE4',
    appId: '1:873700316255:android:21ce3dba9b30eb8fefb7ea',
    messagingSenderId: '873700316255',
    projectId: 'econtrollectricity',
    databaseURL: 'https://econtrollectricity-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'econtrollectricity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvoNH_RQz5xm8uVp_CDKoipXn9TJwszcQ',
    appId: '1:873700316255:ios:d87acd5f052115daefb7ea',
    messagingSenderId: '873700316255',
    projectId: 'econtrollectricity',
    databaseURL: 'https://econtrollectricity-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'econtrollectricity.appspot.com',
    iosBundleId: 'com.example.ipecs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvoNH_RQz5xm8uVp_CDKoipXn9TJwszcQ',
    appId: '1:873700316255:ios:f357d1759d81b7e1efb7ea',
    messagingSenderId: '873700316255',
    projectId: 'econtrollectricity',
    databaseURL: 'https://econtrollectricity-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'econtrollectricity.appspot.com',
    iosBundleId: 'com.example.ipecs.RunnerTests',
  );
}
